apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsu.fullname" . }}-bulker
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
spec:
  {{- if not .Values.bulker.autoscaling.enabled }}
  replicas: {{ .Values.bulker.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "jitsu.selectorLabels" . | nindent 6 }}
      {{- include "jitsu.bulker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
        {{- include "jitsu.bulker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bulker.image.repository }}:{{ .Values.bulker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bulker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bulker.service.port }}
              protocol: TCP
          env:
            {{- $env := merge (deepCopy .Values.bulker.environment) .Values.jitsu.environment -}}
            {{- range $k, $v := $env }}
              - name: {{ $k | quote }}
                {{- toYaml $v | nindent 16 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
