name: Publish Helm chart to Google Artifact Registry
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: stafftastic/helm-publish-action@v2.0.0
        with:
          registry: registry-1.docker.io
          repository: stafftasticcharts
          username: stafftasticpush
          password: ${{secrets.DOCKER_HUB_TOKEN}}
